
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.createcustomer;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621084
 * 2019-07-16T21:36:39.247+05:30
 * Generated source version: 3.0.4.redhat-621084
 * 
 */

@javax.jws.WebService(
                      serviceName = "CreateCustomerEndpointService",
                      portName = "CreateCustomerService",
                      targetNamespace = "http://www.example.org/CreateCustomer/",
                      wsdlLocation = "file:/C:/Users/capiot/workspace/SampleWebServiceExpose/src/main/resources/WSDL/GetFullName.wsdl",
                      endpointInterface = "org.example.createcustomer.CreateCustomerEndpoint")
                      
public class CreateCustomerServiceImpl implements CreateCustomerEndpoint {

    private static final Logger LOG = Logger.getLogger(CreateCustomerServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.createcustomer.CreateCustomerEndpoint#createCustomer(org.example.createcustomer.CreateCustomerRequest  in )*
     */
    public org.example.createcustomer.CreateCustomerResponse createCustomer(CreateCustomerRequest in) { 
        LOG.info("Executing operation createCustomer");
        System.out.println(in);
        try {
            org.example.createcustomer.CreateCustomerResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
